-- =====================================================================
-- RESTRO PRO — Supabase migration 0016
-- 1. sort_order on payment_methods, tables and delivery_areas, so the Settings page can let the
--    owner rearrange them (POS, checkout and the desktop app follow the same order).
--    It is an IDENTITY column: rows created later automatically get the next number, so a new
--    table / area / method appears at the end of the list without any code. Existing rows are
--    numbered once, in their previous order (name; tables: number). Safe to run twice.
-- 2. sales.service_charge and sales.fbr_fee: the dine-in service charge and the FBR invoicing
--    fee that are part of the bill total (the receipt shows them; they are stored here too).
-- =====================================================================

do $$
begin
  if not exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'payment_methods' and column_name = 'sort_order') then
    alter table public.payment_methods add column sort_order bigint generated by default as identity;
    update public.payment_methods p set sort_order = r.rn
      from (select id, row_number() over (partition by restaurant_id order by name) as rn from public.payment_methods) r
      where r.id = p.id;
  end if;

  if not exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'tables' and column_name = 'sort_order') then
    alter table public.tables add column sort_order bigint generated by default as identity;
    update public.tables t set sort_order = r.rn
      from (select id, row_number() over (partition by restaurant_id order by length(number::text), number::text) as rn from public.tables) r
      where r.id = t.id;
  end if;

  if not exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'delivery_areas' and column_name = 'sort_order') then
    alter table public.delivery_areas add column sort_order bigint generated by default as identity;
    update public.delivery_areas d set sort_order = r.rn
      from (select id, row_number() over (partition by restaurant_id order by name) as rn from public.delivery_areas) r
      where r.id = d.id;
  end if;
end $$;

alter table public.sales add column if not exists service_charge numeric not null default 0;
alter table public.sales add column if not exists fbr_fee numeric not null default 0;

notify pgrst, 'reload schema';
